--- scsicmds.cpp.orig	2022-02-27 07:53:55 UTC
+++ scsicmds.cpp
@@ -2198,7 +2198,26 @@ static const char * strs_for_asc_5d[] = {
 static const char * strs_for_asc_b[] = {
        /* 0x00 */   "WARNING",
                "WARNING - SPECIFIED TEMPERATURE EXCEEDED",
-               "WARNING - ENCLOSURE DEGRADED"};
+               "WARNING - ENCLOSURE DEGRADED",
+               "WARNING - BACKGROUND SELF-TEST FAILED",
+               "WARNING - BACKGROUND PRE-SCAN DETECTED MEDIUM ERROR",
+               "WARNING - BACKGROUND MEDIUM SCAN DETECTED MEDIUM ERROR",
+               "WARNING - NON-VOLATILE CACHE NOW VOLATILE",
+               "WARNING - DEGRADED POWER TO NON-VOLATILE CACHE",
+               "WARNING - POWER LOSS EXPECTED",
+               "WARNING - DEVICE STATISTICS NOTIFICATION ACTIVE",
+               "WARNING - HIGH CRITICAL TEMPERATURE LIMIT EXCEEDED",
+               "WARNING - LOW CRITICAL TEMPERATURE LIMIT EXCEEDED",
+               "WARNING - HIGH OPERATING TEMPERATURE LIMIT EXCEEDED",
+               "WARNING - LOW OPERATING TEMPERATURE LIMIT EXCEEDED",
+               "WARNING - HIGH CRITICAL HUMIDITY LIMIT EXCEEDED",
+               "WARNING - LOW CRITICAL HUMIDITY LIMIT EXCEEDED",
+               "WARNING - HIGH OPERATING HUMIDITY LIMIT EXCEEDED",
+               "WARNING - LOW OPERATING HUMIDITY LIMIT EXCEEDED",
+               "WARNING - MICROCODE SECURITY AT RISK",
+               "WARNING - MICROCODE DIGITAL SIGNATURE VALIDATION FAILURE",
+               "WARNING - PHYSICAL ELEMENT STATUS CHANGE"
+};
 
 static char spare_buff[128];
 
