# $FreeBSD$

PORTVERSION=	2.0.4.rc1
# Set PORTREVISION explicitly so it won't be inherited from the MASTERDIR
PORTREVISION=	0
PKGNAMESUFFIX=	-stg

GH_TAGNAME=	2.0.4-rc1

CONFLICTS_INSTALL=	add_mbr

MASTERDIR=	${.CURDIR}/../add_mbr
DISTINFO_FILE=	${.CURDIR}/distinfo

.include "${MASTERDIR}/Makefile"
