# $FreeBSD$

PORTNAME=	storage-cleanup
PORTVERSION=	0.1.0.20230227
CATEGORIES=	axcient
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	jsollvander@axcient.com
COMMENT=	Tool for cleaning up zfs datasets in /to-del/

USES=		axcient python
USE_PYTHON=	autoplist distutils

NO_ARCH=	yes

GH_PROJECT=	vm-storage-cleanup
GH_TAGNAME=	f008096dc9a39433bf428f0dada9998a487da912

.include <bsd.port.mk>
