# $FreeBSD$

PORTNAME=	storage-cleanup
PORTVERSION=	0.1.0.20230925
CATEGORIES=	axcient
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	jsollvander@axcient.com
COMMENT=	Tool for cleaning up zfs datasets in /to-del/

USES=		axcient python
USE_PYTHON=	autoplist distutils

NO_ARCH=	yes

GH_PROJECT=	vm-storage-cleanup
GH_TAGNAME=	3306d53236de33ed340d7816dddf8ad052509bd1

.include <bsd.port.mk>
