# $FreeBSD$

PORTNAME=	storage-cleanup
PORTVERSION=	0.1.0.20220824
CATEGORIES=	axcient
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	jsollvander@axcient.com
COMMENT=	Tool for cleaning up zfs datasets in /to-del/

USES=		axcient python
USE_PYTHON=	autoplist distutils

NO_ARCH=	yes

GH_PROJECT=	vm-storage-cleanup
GH_TAGNAME=	c7a3261041624a9e0d45d672ec324c146de8308f

.include <bsd.port.mk>
