# $FreeBSD$

DISTVERSION=	1.1.0
PORTREVISION=	0
PKGNAMESUFFIX=	-stg

GH_TAGNAME=	vdisk_fuse-1.1.0

CONFLICTS_INSTALL=	vdisk-fuse

MASTERDIR=	${.CURDIR}/../vdisk-fuse
DISTINFO_FILE=	${.CURDIR}/distinfo

.include "${MASTERDIR}/Makefile"
