# $FreeBSD$

DISTVERSION=	1.1.1
PKGNAMESUFFIX=	-stg

GH_TAGNAME=	vdisk_fuse-1.1.1

CONFLICTS_INSTALL=	vdisk-fuse

MASTERDIR=	${.CURDIR}/../vdisk-fuse
DISTINFO_FILE=	${.CURDIR}/distinfo

.include "${MASTERDIR}/Makefile"
