# $FreeBSD$

DISTVERSION=	1.1.3
PKGNAMESUFFIX=	-stg

GH_TAGNAME=	vdisk_fuse-1.1.3
GH_COMMIT_FILE= .gitcommit

CONFLICTS_INSTALL=	vdisk-fuse

MASTERDIR=	${.CURDIR}/../vdisk-fuse
DISTINFO_FILE=	${.CURDIR}/distinfo

.include "${MASTERDIR}/Makefile"
