PORTNAME=	checkrc
DISTVERSION=	0.0.1
CATEGORIES=	sysutils

MAINTAINER=	meka@tilda.center
COMMENT=	Command-line tool designed to validate the configuration settings
WWW=		https://github.com/scovl/checkrc

LICENSE=	BSD2CLAUSE

USE_GITHUB=	yes
GH_ACCOUNT=	scovl
GH_TAGNAME=	aa62616

PLIST_FILES=	bin/checkrc

.include <bsd.port.mk>
