# $FreeBSD$
#

    COMMENT = Proprietary Axcient ports

    SUBDIR += axcient-utils
    SUBDIR += add_mbr
    SUBDIR += add_mbr-dev
    SUBDIR += add_mbr-stg
    SUBDIR += cloudserver
    SUBDIR += cloudserver-stg
    SUBDIR += cloudserver2
    SUBDIR += cloudserver2-dev
    SUBDIR += cloudserver2-stg
    SUBDIR += dcpkg
    SUBDIR += dcpkg-stg
    SUBDIR += dralserver
    SUBDIR += dralserver-dev
    SUBDIR += dralserver-stg
    SUBDIR += efsserver
    SUBDIR += efs-vm-utils
    SUBDIR += grpc-tests-dev
    SUBDIR += migration-tools
    SUBDIR += py-axcient-helpers
    SUBDIR += py-drive-exporter
    SUBDIR += py-malloc-exporter
    SUBDIR += py-pxeweb
    SUBDIR += rsync-proxy
    SUBDIR += rsync-proxy-dev
    SUBDIR += rsync-proxy-stg
    SUBDIR += smart-recovery
    SUBDIR += smart-recovery-dev
    SUBDIR += smart-recovery-stg
    SUBDIR += spxops-vmagent
    SUBDIR += storage-cleanup
    SUBDIR += szs
    SUBDIR += szs-dev    
    SUBDIR += szs-stg
    SUBDIR += szs-migrator
    SUBDIR += vdisk-fuse
    SUBDIR += vdisk-fuse-dev
    SUBDIR += vdisk-fuse-stg
    SUBDIR += vm-migrator
    SUBDIR += vt2
    SUBDIR += vt2-dev    
    SUBDIR += vt2-stg
    SUBDIR += ztop-exporter

.include <bsd.port.subdir.mk>
