# $FreeBSD$
#

    COMMENT = Proprietary Axcient ports

    SUBDIR += axcient-utils
    SUBDIR += add_mbr
    SUBDIR += add_mbr-dev
    SUBDIR += add_mbr-stg
    SUBDIR += cloudserver
    SUBDIR += cloudserver-stg
    SUBDIR += cloudserver2
    SUBDIR += cloudserver2-dev
    SUBDIR += cloudserver2-stg
    SUBDIR += dcpkg
    SUBDIR += dcpkg-stg
    SUBDIR += dralserver
    SUBDIR += dralserver-dev
    SUBDIR += dralserver-stg
    SUBDIR += efsserver
    SUBDIR += efs-vm-utils
    SUBDIR += py-drive-exporter
    SUBDIR += smart-recovery
    SUBDIR += smart-recovery-dev
    SUBDIR += smart-recovery-stg
    SUBDIR += spxops-vmagent
    SUBDIR += szs
    SUBDIR += szs-dev    
    SUBDIR += szs-stg
    SUBDIR += szs-migrator
    SUBDIR += vdisk-fuse
    SUBDIR += vt2
    SUBDIR += vt2-dev    
    SUBDIR += vt2-stg

.include <bsd.port.subdir.mk>
