# $FreeBSD$

DISTVERSION=	1.1.3
PORTREVISION=	0
PKGNAMESUFFIX=	-stg

GH_TAGNAME=	1.1.3

CONFLICTS_INSTALL=	smart-recovery

MASTERDIR=	${.CURDIR}/../smart-recovery
DISTINFO_FILE=	${.CURDIR}/distinfo

.include "${MASTERDIR}/Makefile"
