# $FreeBSD$

DISTVERSION=	1.2.3
PORTREVISION=	0
PKGNAMESUFFIX=	-stg

GH_TAGNAME=	1.2.3
GH_COMMIT_FILE= .gitcommit

CONFLICTS_INSTALL=	smart-recovery

MASTERDIR=	${.CURDIR}/../smart-recovery
DISTINFO_FILE=	${.CURDIR}/distinfo

.include "${MASTERDIR}/Makefile"
