# $FreeBSD$

DISTVERSION=	1.0.4
PORTREVISION=	0
PKGNAMESUFFIX=	-stg

GH_TAGNAME=	1.0.4

CONFLICTS_INSTALL=	smart-recovery

MASTERDIR=	${.CURDIR}/../smart-recovery
DISTINFO_FILE=	${.CURDIR}/distinfo

.include "${MASTERDIR}/Makefile"
