PORTNAME=	py-axcient
PORTVERSION=	0.1.0.20220613
CATEGORIES=	axcient
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	jsollvander@axcient.com
COMMENT=	Shared/boilerplate python code

USES=		axcient python
USE_PYTHON=	autoplist distutils

.include <bsd.port.options.mk>

NO_ARCH=	yes

GH_PROJECT=	py-axcient
GH_TAGNAME=	132d93d56609b56c8a4462b9b9fb4e71e6d3c594

.include <bsd.port.mk>

