# $FreeBSD$

PORTVERSION=	1.1.6.rc1
PORTREVISION=	0
PKGNAMESUFFIX=	-stg

GH_TAGNAME=     1.1.6-rc1

SZS_LIB_DEPENDS= libszs-op.so:axcient/szs-stg
CONFLICTS_INSTALL=	vt2

MASTERDIR=	${.CURDIR}/../vt2
DISTINFO_FILE=	${.CURDIR}/distinfo

.include "${MASTERDIR}/Makefile"
