PORTNAME=	axcient-helpers
PORTVERSION=	0.1.0.20220616
CATEGORIES=	axcient
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	jsollvander@axcient.com
COMMENT=	Shared/boilerplate python code

USES=		axcient python
USE_PYTHON=	autoplist distutils

.include <bsd.port.options.mk>

NO_ARCH=	yes

GH_PROJECT=	py-axcient
GH_TAGNAME=	859acd6b6db5ff7e1e5d8ac609af44679595b0b9

.include <bsd.port.mk>

